# Generated by Django 2.2.6 on 2019-10-26 18:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Название')),
                ('slug', models.SlugField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='Item/%Y/%m/%d/', verbose_name='Изображение товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
            ],
            options={
                'verbose_name': 'Носки',
                'verbose_name_plural': 'Носки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('socks_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='socks_shop.Socks')),
                ('size', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8)),
                ('stock', models.PositiveIntegerField(verbose_name='На складе')),
            ],
            options={
                'verbose_name': 'Экземпляр',
                'verbose_name_plural': 'Экземпляры',
                'ordering': ['name'],
            },
            bases=('socks_shop.socks',),
        ),
    ]
