# Generated by Django 2.2.6 on 2019-10-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socks_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='socks',
            index_together={('id', 'slug')},
        ),
    ]
