# Generated by Django 2.2.6 on 2019-10-28 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socks_shop', '0002_auto_20191026_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Экземпляр',
                'verbose_name_plural': 'Экземпляры',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='socks',
            options={'ordering': ['name'], 'verbose_name': 'Наименование', 'verbose_name_plural': 'Наименования'},
        ),
        migrations.AddField(
            model_name='socks',
            name='color',
            field=models.CharField(db_index=True, max_length=30, null=True, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='socks',
            name='name',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='socks',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='Instance',
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socks_shop.Socks', verbose_name='Наименование'),
        ),
    ]
