# Generated by Django 2.2.6 on 2019-10-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socks_shop', '0004_auto_20191028_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socks',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение товара'),
        ),
    ]
