# Generated by Django 2.2.6 on 2019-10-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socks_shop', '0005_auto_20191028_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.SlugField>/', verbose_name='Изображение товара'),
        ),
    ]
