# Generated by Django 2.2.6 on 2019-11-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socks_shop', '0006_auto_20191028_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%D/', verbose_name='Изображение товара'),
        ),
    ]
