version: "2.4"

services:
  django-app:
    build:
      context:
        django-app/build

    volumes:
      - ./django-app/django_shop:/app

    ports:
      - 8000:8000

    env_file: .env

    depends_on:
      - db

    command: bash -c "python3.8 manage.py makemigrations &&
                      python3.8 manage.py migrate &&
                      python3.8 manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:9.6

    env_file: .env

    volumes:
      - ./db/volumes/pgdata:/var/lib/postgresql/data/pgdata

    ports:
      - 5433:5432

